version: "3.4"

services:
  robot-race-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    ports:
      - "${PORT}:8080"
  robot-race-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    scale: 1
  redis:
    restart: always
    image: redis:6.2
    volumes:
      - ./volumes/redis:/data
