version: "3.4"

services:
  robot-race:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - NODE_ENV="production"
      - HUSKY=0
      - REDIS_URL=redis://redis
    ports:
      - "8080:8080"
  redis:
    image: redis:6.2
    ports:
      - "5052:6379"
    volumes:
      - ./volumes/redis:/data

volumes:
  redis-data-robot-race:
